project:
  type: website
  output-dir: docs
website:
  title: "Yoseph's ML Blog"
  repo-url: 'https://github.com/yosephberhanu/ml-blog'
  repo-actions: [source]
  navbar:
    left:
      - href: index.qmd
        text: Blog
      - href: CS5805.qmd
        text: About

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
