project:
  type: website
  output-dir: docs
website:
  title: "Yoseph's ML Blog"
  navbar:
    left:
      - href: index.qmd
        text: Blog
      - href: CS5805.qmd
        text: About

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
