<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Yoseph Berhanu">
<meta name="dcterms.date" content="2023-12-08">
<meta name="description" content="What’s PCA, and how to calculate it">

<title>Yoseph’s ML Blog - Principal Component Analysis</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script>
<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Yoseph’s ML Blog</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html" rel="" target="">
 <span class="menu-text">Blog</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../CS5805.html" rel="" target="">
 <span class="menu-text">About</span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools ms-auto">
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a>
  <ul class="collapse">
  <li><a href="#what-exactly-is-principal-component" id="toc-what-exactly-is-principal-component" class="nav-link" data-scroll-target="#what-exactly-is-principal-component">What Exactly is Principal Component</a></li>
  <li><a href="#load-the-data" id="toc-load-the-data" class="nav-link" data-scroll-target="#load-the-data">Load the data</a></li>
  <li><a href="#maximum-minimum-standard-deviation-and-average-values" id="toc-maximum-minimum-standard-deviation-and-average-values" class="nav-link" data-scroll-target="#maximum-minimum-standard-deviation-and-average-values">Maximum, Minimum, Standard deviation and Average Values</a></li>
  </ul></li>
  <li><a href="#computing-pca" id="toc-computing-pca" class="nav-link" data-scroll-target="#computing-pca">Computing PCA</a></li>
  <li><a href="#pca-in-action" id="toc-pca-in-action" class="nav-link" data-scroll-target="#pca-in-action">PCA in Action</a>
  <ul class="collapse">
  <li><a href="#step-1.-standardization" id="toc-step-1.-standardization" class="nav-link" data-scroll-target="#step-1.-standardization">Step 1. Standardization</a></li>
  <li><a href="#step-2.-covariance-matrix" id="toc-step-2.-covariance-matrix" class="nav-link" data-scroll-target="#step-2.-covariance-matrix">Step 2. Covariance Matrix</a></li>
  <li><a href="#step-3.-eigenvectors-and-eigenvalues" id="toc-step-3.-eigenvectors-and-eigenvalues" class="nav-link" data-scroll-target="#step-3.-eigenvectors-and-eigenvalues">Step 3. Eigenvectors and Eigenvalues</a></li>
  <li><a href="#step-4.-feature-vector" id="toc-step-4.-feature-vector" class="nav-link" data-scroll-target="#step-4.-feature-vector">Step 4. Feature Vector</a></li>
  <li><a href="#step-5.-recast-the-data" id="toc-step-5.-recast-the-data" class="nav-link" data-scroll-target="#step-5.-recast-the-data">Step 5. Recast the Data</a></li>
  <li><a href="#using-scikit-learn-package" id="toc-using-scikit-learn-package" class="nav-link" data-scroll-target="#using-scikit-learn-package">Using <code>scikit-learn</code> package</a></li>
  </ul></li>
  </ul>
<div class="toc-actions"><div><i class="bi bi-github"></i></div><div class="action-links"><p><a href="https://github.com/yosephberhanu/ml-blog/blob/main/posts/pca.qmd" class="toc-action">View source</a></p></div></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Principal Component Analysis</h1>
  <div class="quarto-categories">
    <div class="quarto-category">Probability theory</div>
    <div class="quarto-category">PCA</div>
  </div>
  </div>

<div>
  <div class="description">
    What’s PCA, and how to calculate it
  </div>
</div>


<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Yoseph Berhanu </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">December 8, 2023</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<p>Banner Image Credit: <a href="https://www.flickr.com/photos/91261194@N06/">Jernej Furman</a></p>
<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<p>Principal component analysis (PCA) is a widely used statistical method for examining extensive datasets characterized by numerous dimensions or features per observation. PCA is a relatively well-established theory with its roots dating back to the beginning of the 1900s. Its primary aim is to enhance data interpretability while conserving the maximum information possible, thereby enabling the visualization of multidimensional data. Essentially, PCA serves as a statistical approach to diminish dataset dimensionality. This is achieved by transforming the data through linear methods into a fresh coordinate system where a reduced number of dimensions can effectively encapsulate (most of) the data variation compared to the original dataset.</p>
<p>In various studies, researchers often employ the initial two principal components to plot data in a two-dimensional space, facilitating the identification of clusters among closely associated data points. The applications of principal component analysis span across diverse fields including population genetics, microbiome studies, and atmospheric science. As Machine Learning(ML) is a data-driven approach to building algorithms, PCA plays an important role in ML for Dimensionality Reduction, Data Preprocessing, Visualization, Decorrelation and Feature Extraction, Speeding Up Learning Algorithms, and Noise Filtering.</p>
<p>The idea behind PCA is, that given a dataset with some statistical distribution (i.e., not deterministic), we would like to find features that can best describe as much of the data as possible. By doing so we will be able to explain the data with fewer sets of features than the actual data has. In data involving numerous variables and dimensions, not all variables hold equal importance. Some variables are key while others are less critical. The Principal Component Analysis (PCA) method offers a systematic way to identify and eliminate less significant variables. By transforming the original variables into uncorrelated principal components, PCA retains essential information while discarding less important variables. This process simplifies complex datasets by focusing on the principal components that capture the majority of the dataset’s variance. Consequently, PCA enhances data transparency by emphasizing the critical factors while reducing unnecessary complexity.</p>
<p>In this blog, we will go through the steps for calculating PCA with an example data set demonstrating PCA in action to perform dimensionality reduction.</p>
<section id="what-exactly-is-principal-component" class="level3">
<h3 class="anchored" data-anchor-id="what-exactly-is-principal-component">What Exactly is Principal Component</h3>
<p>The principal component represents a novel feature or feature formed by combining the original features linearly. By crafting one or more of these new features, the objective is to ensure that these combinations result in uncorrelated variables, known as principal components. This process involves condensing or compressing most of the information from the initial variables into the first component. In essence, when dealing with n-dimensional data, PCA generates n principal components. However, the primary goal of PCA is to maximize information encapsulation in the initial component, followed by retaining the maximum remaining information in subsequent components. This systematic approach prioritizes the encapsulation of significant data details within these newly constructed components in a step-by-step manner.</p>
<p>Arranging information within principal components enables effective dimensionality reduction without significant loss of information. This process involves discarding components that hold minimal information while regarding the remaining components as the new variables. By prioritizing the retention of informative components and disregarding those with lower significance, one can streamline the dataset and create a new set of variables that effectively captures the essential information from the original dataset. This approach facilitates a more concise representation of the data while preserving the most critical information contained within the retained components. While representing data with less number of features reduces the complexity of the data aiding in different aspects of machine learning it complicates understanding of the data as the newly formed features (i.e., principal components) do not have a one-to-one mapping with the original feature set. ## Data The data we will use in this post comes with <a href="https://seaborn.pydata.org/">seaborn</a> plotting package. Specifically, we’ll use the <code>car_crashes</code> dataset from seaborn package. If you’re new to <code>seaborn</code>, I’ve <a href="../posts/seaborn_demo.html">another</a> post that demonstrates different plot types available in seaborn.</p>
<p>The <code>car_crashes</code> dataset is data about car accidents, their cause, and cost to insurance companies in the states of the USA. It consists of the following features.</p>
<ul>
<li><strong>total</strong>: Number of drivers involved in fatal collisions per billion miles (5.900–23.900)</li>
<li><strong>speeding</strong>: Percentage Of Drivers Involved In Fatal Collisions Who Were Speeding (1.792–9.450)</li>
<li><strong>alcohol</strong>: Percentage Of Drivers Involved In Fatal Collisions Who Were Alcohol-Impaired (1.593–10.038)</li>
<li><strong>not_distracted</strong>: Percentage Of Drivers Involved In Fatal Collisions Who Were Not Distracted (1.760–23.661)</li>
<li><strong>no_previous</strong>: Percentage Of Drivers Involved In Fatal Collisions Who Had Not Been Involved In Any Previous Accidents (5.900–21.280)</li>
<li><strong>ins_premium</strong>: Car Insurance Premiums (641.960–1301.520)</li>
<li><strong>ins_losses</strong>: Losses incurred by insurance companies for collisions per insured driver (82.75–194.780)</li>
<li><strong>abbrev</strong>: A two-letter abbreviation of US state name the data stands for</li>
</ul>
<section id="import-the-required-packages" class="level4">
<h4 class="anchored" data-anchor-id="import-the-required-packages">Import the required packages</h4>
<p>Let’s start by importing the necessary packages</p>
<div class="cell" data-execution_count="1">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> seaborn <span class="im">as</span> sns</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="load-the-data" class="level3">
<h3 class="anchored" data-anchor-id="load-the-data">Load the data</h3>
<p>We can now load the data and try to understand it</p>
<div class="cell" data-execution_count="2">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>car_crashes <span class="op">=</span> sns.load_dataset(<span class="st">"car_crashes"</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>car_crashes.head()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="342">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">total</th>
<th data-quarto-table-cell-role="th">speeding</th>
<th data-quarto-table-cell-role="th">alcohol</th>
<th data-quarto-table-cell-role="th">not_distracted</th>
<th data-quarto-table-cell-role="th">no_previous</th>
<th data-quarto-table-cell-role="th">ins_premium</th>
<th data-quarto-table-cell-role="th">ins_losses</th>
<th data-quarto-table-cell-role="th">abbrev</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>18.8</td>
<td>7.332</td>
<td>5.640</td>
<td>18.048</td>
<td>15.040</td>
<td>784.55</td>
<td>145.08</td>
<td>AL</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>18.1</td>
<td>7.421</td>
<td>4.525</td>
<td>16.290</td>
<td>17.014</td>
<td>1053.48</td>
<td>133.93</td>
<td>AK</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>18.6</td>
<td>6.510</td>
<td>5.208</td>
<td>15.624</td>
<td>17.856</td>
<td>899.47</td>
<td>110.35</td>
<td>AZ</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>22.4</td>
<td>4.032</td>
<td>5.824</td>
<td>21.056</td>
<td>21.280</td>
<td>827.34</td>
<td>142.39</td>
<td>AR</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>12.0</td>
<td>4.200</td>
<td>3.360</td>
<td>10.920</td>
<td>10.680</td>
<td>878.41</td>
<td>165.63</td>
<td>CA</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>We can see all features except the abbreviation (which represents the US state the sample stands for) are continuous-valued.</p>
<div class="cell" data-execution_count="3">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>car_crashes.info()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>&lt;class 'pandas.core.frame.DataFrame'&gt;
RangeIndex: 51 entries, 0 to 50
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   total           51 non-null     float64
 1   speeding        51 non-null     float64
 2   alcohol         51 non-null     float64
 3   not_distracted  51 non-null     float64
 4   no_previous     51 non-null     float64
 5   ins_premium     51 non-null     float64
 6   ins_losses      51 non-null     float64
 7   abbrev          51 non-null     object 
dtypes: float64(7), object(1)
memory usage: 3.3+ KB</code></pre>
</div>
</div>
<p>We’ll remove the apprev column as it is not relevant to our demonstration in this post</p>
<div class="cell" data-execution_count="4">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>car_crashes <span class="op">=</span> car_crashes.drop(<span class="st">'abbrev'</span>, axis<span class="op">=</span><span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="maximum-minimum-standard-deviation-and-average-values" class="level3">
<h3 class="anchored" data-anchor-id="maximum-minimum-standard-deviation-and-average-values">Maximum, Minimum, Standard deviation and Average Values</h3>
<p>The maximum value in each of the columns</p>
<div class="cell" data-execution_count="5">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>car_crashes.<span class="bu">max</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="345">
<pre><code>total               23.900
speeding             9.450
alcohol             10.038
not_distracted      23.661
no_previous         21.280
ins_premium       1301.520
ins_losses         194.780
dtype: float64</code></pre>
</div>
</div>
<p>The minimum value in each of the columns</p>
<div class="cell" data-execution_count="6">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>car_crashes.<span class="bu">min</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="346">
<pre><code>total               5.900
speeding            1.792
alcohol             1.593
not_distracted      1.760
no_previous         5.900
ins_premium       641.960
ins_losses         82.750
dtype: float64</code></pre>
</div>
</div>
<p>The range in each column is the difference between the max and minimum values</p>
<div class="cell" data-execution_count="7">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>car_crashes_range <span class="op">=</span> car_crashes.<span class="bu">max</span>() <span class="op">-</span> car_crashes.<span class="bu">min</span>()</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>car_crashes_range</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="347">
<pre><code>total              18.000
speeding            7.658
alcohol             8.445
not_distracted     21.901
no_previous        15.380
ins_premium       659.560
ins_losses        112.030
dtype: float64</code></pre>
</div>
</div>
<p>We can visualize the difference in the range</p>
<div class="cell" data-execution_count="8">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>p1 <span class="op">=</span> car_crashes_range.plot(</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>    legend<span class="op">=</span><span class="va">False</span>,</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>    kind<span class="op">=</span><span class="st">"bar"</span>,</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>    rot<span class="op">=</span><span class="dv">45</span>,</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>    color<span class="op">=</span><span class="st">"blue"</span>,</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>    fontsize<span class="op">=</span><span class="dv">16</span>,</span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>p1.set_title(<span class="st">"Range of values in our car crash data"</span>, fontsize<span class="op">=</span><span class="dv">16</span>)</span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a>p1.set_xlabel(<span class="st">"Feature"</span>, fontsize<span class="op">=</span><span class="dv">14</span>)</span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a>p1.set_ylabel(<span class="st">"Range"</span>, fontsize<span class="op">=</span><span class="dv">14</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="348">
<pre><code>Text(0, 0.5, 'Range')</code></pre>
</div>
<div class="cell-output cell-output-display">
<p><img src="pca_files/figure-html/cell-9-output-2.png" width="622" height="570"></p>
</div>
</div>
<p>We can get the mean value and standard deviation of each column as well</p>
<div class="cell" data-execution_count="9">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>car_crashes.mean(axis<span class="op">=</span><span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="349">
<pre><code>total              15.790196
speeding            4.998196
alcohol             4.886784
not_distracted     13.573176
no_previous        14.004882
ins_premium       886.957647
ins_losses        134.493137
dtype: float64</code></pre>
</div>
</div>
<div class="cell" data-execution_count="10">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>car_crashes.std(axis<span class="op">=</span><span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="350">
<pre><code>total               4.122002
speeding            2.017747
alcohol             1.729133
not_distracted      4.508977
no_previous         3.764672
ins_premium       178.296285
ins_losses         24.835922
dtype: float64</code></pre>
</div>
</div>
</section>
</section>
<section id="computing-pca" class="level2">
<h2 class="anchored" data-anchor-id="computing-pca">Computing PCA</h2>
<p>Calculating PCA involves five steps. These are</p>
<ol type="1">
<li>Standardization</li>
<li>Covariance Matrix Computation</li>
<li>Eigenvectors and Eigenvalues</li>
<li>Feature Vector</li>
<li>Recast the Data</li>
</ol>
<p>Now that we’ve explained the data we’ll use for demonstrating PCA and the steps involved, let’s go through each step with the aforementioned data and see PCA in action.</p>
</section>
<section id="pca-in-action" class="level2">
<h2 class="anchored" data-anchor-id="pca-in-action">PCA in Action</h2>
<section id="step-1.-standardization" class="level3">
<h3 class="anchored" data-anchor-id="step-1.-standardization">Step 1. Standardization</h3>
<p>PCA is sensitive to variance, meaning if features different range in values the PCA calculation will be dominated by features with a larger range. In our dataset, we have features that represent a percentage value (hence the potential values range from 0 to 100, but the actual maximum value in the dataset is way below 100). We also have other features that have a more inconsistent range. For example, the <code>ins_premium</code> has a range of <code>659.560</code> while <code>speading</code> has a range of <code>7.658</code>. As a result, the PCA analysis will be greatly (and incorrectly) influenced by a change in <code>ins_premium</code> value.</p>
<p>To address this issue, we perform standardization before PCA, that is we bring values of all features to a standard range. The one common way to standardize any data is the following formula.</p>
<p><span class="math display">\[
z = \frac{v - \mu}{\sigma}
\]</span> Where <span class="math inline">\(z\)</span> is the standardized value, <span class="math inline">\(v\)</span> is the original value, <span class="math inline">\(\mu\)</span> stands for mean and <span class="math inline">\(\sigma\)</span> is the standard deviation</p>
<p>We can perform this calculation in python as follows</p>
<div class="cell" data-execution_count="11">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>car_crashes_std <span class="op">=</span> (car_crashes <span class="op">-</span> car_crashes.mean(axis<span class="op">=</span><span class="dv">0</span>)) <span class="op">/</span> car_crashes.std(axis<span class="op">=</span><span class="dv">0</span>)</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>car_crashes_std.head()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="351">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">total</th>
<th data-quarto-table-cell-role="th">speeding</th>
<th data-quarto-table-cell-role="th">alcohol</th>
<th data-quarto-table-cell-role="th">not_distracted</th>
<th data-quarto-table-cell-role="th">no_previous</th>
<th data-quarto-table-cell-role="th">ins_premium</th>
<th data-quarto-table-cell-role="th">ins_losses</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>0.730180</td>
<td>1.156638</td>
<td>0.435603</td>
<td>0.992425</td>
<td>0.274956</td>
<td>-0.574368</td>
<td>0.426272</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>0.560360</td>
<td>1.200747</td>
<td>-0.209229</td>
<td>0.602537</td>
<td>0.799304</td>
<td>0.933964</td>
<td>-0.022674</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>0.681660</td>
<td>0.749253</td>
<td>0.185767</td>
<td>0.454831</td>
<td>1.022962</td>
<td>0.070177</td>
<td>-0.972106</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>1.603542</td>
<td>-0.478849</td>
<td>0.542015</td>
<td>1.659539</td>
<td>1.932471</td>
<td>-0.334374</td>
<td>0.317961</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>-0.919504</td>
<td>-0.395588</td>
<td>-0.882977</td>
<td>-0.588421</td>
<td>-0.883180</td>
<td>-0.047941</td>
<td>1.253703</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>Let’s perform a similar visualization on the range as we did earlier</p>
<div class="cell" data-execution_count="12">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>p2 <span class="op">=</span> (car_crashes_std.<span class="bu">max</span>() <span class="op">-</span> car_crashes_std.<span class="bu">min</span>()).plot(</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>    legend<span class="op">=</span><span class="va">False</span>, kind<span class="op">=</span><span class="st">"bar"</span>, rot<span class="op">=</span><span class="dv">45</span>, color<span class="op">=</span><span class="st">"blue"</span>, fontsize<span class="op">=</span><span class="dv">16</span></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>p2.set_title(<span class="st">"Range of values in our car crash data after standardization"</span>, fontsize<span class="op">=</span><span class="dv">16</span>)</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>p2.set_xlabel(<span class="st">"Features"</span>, fontsize<span class="op">=</span><span class="dv">14</span>)</span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>p2.set_ylabel(<span class="st">"Range"</span>, fontsize<span class="op">=</span><span class="dv">14</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="352">
<pre><code>Text(0, 0.5, 'Range')</code></pre>
</div>
<div class="cell-output cell-output-display">
<p><img src="pca_files/figure-html/cell-13-output-2.png" width="649" height="570"></p>
</div>
</div>
<p>We can see that now the range is more consistent across the features</p>
</section>
<section id="step-2.-covariance-matrix" class="level3">
<h3 class="anchored" data-anchor-id="step-2.-covariance-matrix">Step 2. Covariance Matrix</h3>
<p>Covariance Matrix To get a sense of how the values of the input dataset vary from the mean to each other we compute the covariance matrix. The covariance matrix is a <span class="math inline">\(m × m\)</span> symmetric matrix (where m is the number of features, we’ve in our input dataset). Features might be highly correlated and through computing the covariance matrix we can identify this relationship.</p>
<p>For example, a covariance matrix of an input dataset with 4 features <span class="math inline">\((f_1,f_2,f_3,f_4)\)</span> will be a 4x4 matrix of the following form</p>
<p><span class="math display">\[
Covariance Matrix = \begin{bmatrix}
      cov(f_1,f_1) &amp; cov(f_1,f_2) &amp; cov(f_1,f_3) &amp; cov(f_1,f_4) \\
      cov(f_2,f_1) &amp; cov(f_2,f_2) &amp; cov(f_2,f_3) &amp; cov(f_2,f_4) \\
      cov(f_3,f_1) &amp; cov(f_3,f_2) &amp; cov(f_3,f_3) &amp; cov(f_3,f_4) \\
      cov(f_4,f_1) &amp; cov(f_4,f_2) &amp; cov(f_3,f_3) &amp; cov(f_4,f_4)
\end{bmatrix}
\]</span></p>
<p>We compute the covariance between to features <span class="math inline">\(f_x\)</span> and <span class="math inline">\(f_y\)</span> as follows <span class="math display">\[
cov(f_x,f_y) = \dfrac{\sum(x_i-\mu_x) (y_i-\mu_y)}{n}
\]</span> Where <span class="math inline">\(x_i\)</span> and <span class="math inline">\(y_i\)</span> are the <span class="math inline">\(i^{th}\)</span> values for feature <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span> and <span class="math inline">\(n\)</span> is the total number of data points.</p>
<p>With this equation notice how</p>
<ul>
<li>covariance of a feature f with itself (i.e., <span class="math inline">\(Cov(f_x,f_x)\)</span>) the variance of the feature (i.e., <span class="math inline">\(Var(f_x)\)</span>)</li>
<li>covariance is symmetric, i.e., <span class="math inline">\(Cov(fx,fy) = Cov(f_y,f_x)\)</span></li>
</ul>
<p>Now that we know that the covariance matrix is not more than a table that summarizes the correlations between all the possible pairs of variables, let’s move to the next step. While we can use these equations to calculate the covariance matrix pandas provide a built-in method for calculating it in one go.</p>
<div class="cell" data-execution_count="13">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>cov_mat <span class="op">=</span> car_crashes_std.cov()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We can visualize this matrix using <code>seaborn</code>’s heatmap</p>
<div class="cell" data-execution_count="14">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>sns.heatmap(cov_mat, annot<span class="op">=</span><span class="va">True</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="354">
<pre><code>&lt;Axes: &gt;</code></pre>
</div>
<div class="cell-output cell-output-display">
<p><img src="pca_files/figure-html/cell-15-output-2.png" width="616" height="499"></p>
</div>
</div>
</section>
<section id="step-3.-eigenvectors-and-eigenvalues" class="level3">
<h3 class="anchored" data-anchor-id="step-3.-eigenvectors-and-eigenvalues">Step 3. Eigenvectors and Eigenvalues</h3>
<p>Eigenvectors and eigenvalues, fundamental concepts from linear algebra, play a crucial role in computing the principal components of a dataset from its covariance matrix. In an n-dimensional dataset comprising n features, there exist n eigenvectors accompanied by n corresponding eigenvalues.</p>
<p>Eigenvectors derived from the Covariance matrix represent the axes’ directions where the highest variance or most information is concentrated. These eigenvectors are termed Principal Components. Eigenvalues, on the other hand, serve as coefficients associated with eigenvectors, signifying the quantity of variance encapsulated within each Principal Component. Essentially, eigenvalues provide a measure of the amount of variance carried by the respective eigenvectors, highlighting their significance in determining the variance distribution across the dataset’s principal axes.</p>
<p>Arranging your eigenvectors based on their corresponding eigenvalues, from highest to lowest, provides the principal components in descending order of significance. This ranking scheme ensures that the principal components are prioritized based on the amount of variance or information they encapsulate. The eigenvector associated with the highest eigenvalue represents the most significant principal component, followed by subsequent components in decreasing order of importance, allowing for a systematic determination of the most influential axes within the dataset.</p>
<p>We can use <code>numpy</code>’s <code>linalg.eigh( )</code> method to calcuate eigenvectors and eigenvalues a matrix.</p>
<div class="cell" data-execution_count="15">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>eigen_values, eigen_vectors <span class="op">=</span> np.linalg.eigh(cov_mat)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-execution_count="16">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>eigen_values</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="356">
<pre><code>array([0.02747434, 0.19865996, 0.28077   , 0.350529  , 0.55060199,
       1.57801295, 4.01395176])</code></pre>
</div>
</div>
<div class="cell" data-execution_count="17">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>eigen_vectors</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="357">
<pre><code>array([[ 0.80082487, -0.16970508, -0.14597659, -0.0389558 ,  0.26908802,
        -0.06893769, -0.47947078],
       [ 0.01784783, -0.22479246,  0.02282818,  0.36374887, -0.81826935,
        -0.0765846 , -0.37534719],
       [-0.15285774,  0.7837677 , -0.35479821, -0.14834351, -0.08293253,
        -0.03345835, -0.45437635],
       [-0.14247844,  0.08510479,  0.85646854, -0.1712655 ,  0.12616845,
        -0.04237473, -0.4380328 ],
       [-0.55875371, -0.50401185, -0.33611019, -0.03948141,  0.31798812,
        -0.0961294 , -0.45703414],
       [ 0.04126619, -0.11577348, -0.04214531, -0.65639617, -0.25614247,
        -0.6852266 ,  0.1308319 ],
       [-0.02804966,  0.17805184,  0.06327152,  0.61839859,  0.26173503,
        -0.71252436,  0.06996048]])</code></pre>
</div>
</div>
<p>We should now sort the Eigenvalues in the descending order along with their corresponding Eigenvector.</p>
<div class="cell" data-execution_count="18">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co"># sort the eigenvalues in descending order</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>sorted_index <span class="op">=</span> np.argsort(eigen_values)[::<span class="op">-</span><span class="dv">1</span>]</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>sorted_eigenvalue <span class="op">=</span> eigen_values[sorted_index]</span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Similarly sort the eigenvectors</span></span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a>sorted_eigenvectors <span class="op">=</span> eigen_vectors[:, sorted_index]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="step-4.-feature-vector" class="level3">
<h3 class="anchored" data-anchor-id="step-4.-feature-vector">Step 4. Feature Vector</h3>
<p>Once sorted, we can select the subset of the Eigenvalue as per our requirement. In this case, since we are interested in the two principal components, we take the first two values (i.e.&nbsp;n_components = 2). This forms our feature vector which is a matrix that has as columns the eigenvectors of the components that we decide to keep. By only keeping a subset of the Eigenvectors we are reducing the number of features hence the notion of dimensionality reduction.</p>
<div class="cell" data-execution_count="19">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>n_components <span class="op">=</span> <span class="dv">2</span> </span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>feature_vector <span class="op">=</span> sorted_eigenvectors[:,<span class="dv">0</span>:n_components]</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>feature_vector</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="359">
<pre><code>array([[-0.47947078, -0.06893769],
       [-0.37534719, -0.0765846 ],
       [-0.45437635, -0.03345835],
       [-0.4380328 , -0.04237473],
       [-0.45703414, -0.0961294 ],
       [ 0.1308319 , -0.6852266 ],
       [ 0.06996048, -0.71252436]])</code></pre>
</div>
</div>
</section>
<section id="step-5.-recast-the-data" class="level3">
<h3 class="anchored" data-anchor-id="step-5.-recast-the-data">Step 5. Recast the Data</h3>
<div class="cell" data-execution_count="20">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>car_crash_reduced <span class="op">=</span> <span class="op">-</span>np.dot(</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>    feature_vector.transpose(), car_crashes_std.transpose()</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>).transpose()</span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>cars_pca <span class="op">=</span> pd.DataFrame(data<span class="op">=</span>car_crash_reduced, columns<span class="op">=</span>[<span class="st">"PC 1"</span>, <span class="st">"PC 2"</span>])</span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>cars_pca.head()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="360">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">PC 1</th>
<th data-quarto-table-cell-role="th">PC 2</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>1.587871</td>
<td>0.132134</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>1.132939</td>
<td>0.849778</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>1.418062</td>
<td>-0.416363</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>2.467035</td>
<td>0.345530</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>-1.733390</td>
<td>0.627382</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</section>
<section id="using-scikit-learn-package" class="level3">
<h3 class="anchored" data-anchor-id="using-scikit-learn-package">Using <code>scikit-learn</code> package</h3>
<p>The <code>scikit-learn</code> package comes with an API to calculate PCA without having to follow the above steps</p>
<div class="cell" data-execution_count="21">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.decomposition <span class="im">import</span> PCA</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>pca <span class="op">=</span> PCA(n_components<span class="op">=</span><span class="dv">2</span>)</span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a>pcs <span class="op">=</span> pca.fit_transform(car_crashes_std)</span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a>principal_cars <span class="op">=</span> pd.DataFrame(data<span class="op">=</span>pcs, columns<span class="op">=</span>[<span class="st">"PC 1"</span>, <span class="st">"PC 2"</span>])</span>
<span id="cb33-8"><a href="#cb33-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-9"><a href="#cb33-9" aria-hidden="true" tabindex="-1"></a>principal_cars.head()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="361">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">PC 1</th>
<th data-quarto-table-cell-role="th">PC 2</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>1.587871</td>
<td>0.132134</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>1.132939</td>
<td>0.849778</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>1.418062</td>
<td>-0.416363</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>2.467035</td>
<td>0.345530</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>-1.733390</td>
<td>0.627382</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>One advantage of the <code>scikit-learn</code> implementation of PCA is that it implements <em>Probabilistic Principal Component Analysis</em> <a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a>. This enables us obtain the log maximum-likelihood of each sample. Maximum likelihood refers to the point (in mean or standard deviation) the distribution we’ve is going to represent most of the data we are trying to model.</p>
<div class="cell" data-execution_count="22">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>pca.score_samples(car_crashes_std)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="362">
<pre><code>array([ -6.44954331,  -7.53883983,  -6.40958592, -11.35786508,
        -6.61054168,  -5.03977718,  -7.12053256,  -5.96378314,
       -10.50232239,  -8.20041332,  -6.42991259, -10.97177485,
        -7.06959704,  -4.9868997 ,  -5.54486928,  -7.78448959,
        -5.31230145,  -7.44998984,  -9.88242453,  -6.02864696,
        -8.31301121,  -6.69510241,  -6.02183068,  -6.18648717,
       -20.56341095,  -6.28341612, -12.20777983,  -8.11910771,
        -4.96080412,  -5.43102784,  -8.87161592,  -8.04646994,
        -7.11756172,  -5.79150497, -12.14066975,  -6.12536757,
        -8.30172833,  -5.96072048,  -8.82359145,  -6.85850641,
        -9.58963574,  -6.04225252,  -7.74060643,  -6.44307295,
        -7.73434658,  -5.14398609,  -7.48886884,  -6.43042227,
        -7.67794805,  -9.04404655,  -5.75015305])</code></pre>
</div>
</div>
<p>These values represent how much of the data (likelihood) our PCA components are covering. To get an average value we can use a different method from PCA as follows</p>
<div class="cell" data-execution_count="23">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>pca.score(car_crashes_std)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="363">
<pre><code>-7.61880713471763</code></pre>
</div>
</div>
<p>The log-likelihood value for a given model can range from negative infinity to positive infinity. The actual log-likelihood value for a given model is mostly meaningless, but it’s useful for comparing two or more models. We can compare our previous PCA model with one that has 3, 4, 5 components</p>
<div class="cell" data-execution_count="24">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>pca3 <span class="op">=</span> PCA(n_components<span class="op">=</span><span class="dv">3</span>)</span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>pcs3 <span class="op">=</span> pca3.fit_transform(car_crashes_std)</span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a>pca3.score(car_crashes_std)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="364">
<pre><code>-7.408329581463735</code></pre>
</div>
</div>
<div class="cell" data-execution_count="25">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>pca4 <span class="op">=</span> PCA(n_components<span class="op">=</span><span class="dv">4</span>)</span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>pcs4 <span class="op">=</span> pca4.fit_transform(car_crashes_std)</span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a>pca4.score(car_crashes_std)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="365">
<pre><code>-7.297318147783873</code></pre>
</div>
</div>
<div class="cell" data-execution_count="26">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>pca5 <span class="op">=</span> PCA(n_components<span class="op">=</span><span class="dv">5</span>)</span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>pcs5 <span class="op">=</span> pca5.fit_transform(car_crashes_std)</span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a>pca5.score(car_crashes_std)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="366">
<pre><code>-7.149503033441305</code></pre>
</div>
</div>
<p>While there is an improvement in the actual score we are increasing the number of components. Since our objective is to reduce the number of dimensions (features) and adding more components works against that aim, the improvements gained in log-likelihood score are not worth the additional dimensions we are introducing.</p>


</section>
</section>


<div id="quarto-appendix" class="default"><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Footnotes</h2>

<ol>
<li id="fn1"><p>“Mixtures of Probabilistic Principal Component Analysers” - Michael E. Tipping and Christopher M. Bishop http://www.miketipping.com/papers/met-mppca.pdf<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>